In [37]:
import pandas as pd
import numpy as np
from sklearn.metrics import log_loss
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.model_selection import train_test_split

In [38]:
df = pd.DataFrame(np.array([[0,0,0],[0,1,1],[1,0,1],[1,1,0]]),columns=['x1','x2','label'])

In [39]:
W = np.random.rand(2,1)
W.shape

(2, 1)

In [40]:
x=np.array(df[['x1','x2']])
y=np.array(df['label'])
x=x.T
x,y

(array([[0, 0, 1, 1],
        [0, 1, 0, 1]]),
 array([0, 1, 1, 0]))

In [41]:
Z = np.dot(W.T,x,) + b

In [42]:
Z[:]

array([[0.54154677, 0.89225074, 0.98458127, 1.33528524]])

In [43]:

def sigmoid(z):
    return 1/(1 + np.exp(-z))

In [44]:
A = [sigmoid(z) for z in Z[0]]
A,y

([0.6321721628883264,
  0.7093544271474037,
  0.728016294785521,
  0.7917135313891797],
 array([0, 1, 1, 0]))

In [45]:
from sklearn.metrics import log_loss
J = log_loss(y,A)
J

0.8074532515760618

In [46]:
alpha = 0.0001
for i in range (1000):
    Z =np.dot(W.T,x)+b
    A = sigmoid(Z)
    A = np.where(A < 0.5, 0, 1)
    A = A.squeeze()
    
    J = log_loss(y,A)
    print(J)
    
    dz = A - y
    dz = np.expand_dims(dz,axis = 0)
    dw =  np.dot(x,dz.T)/x.shape[0]
    db = np.sum(dz,axis =1)/x.shape[0]
    W = W - alpha * dw
    b = b - alpha * db

17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.2697879

17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.26978799617044
17.2697879

In [49]:
from sklearn.metrics import confusion_matrix
K=confusion_matrix(y,A)
K

array([[0, 2],
       [0, 2]], dtype=int64)

In [50]:
y

array([0, 1, 1, 0])

In [51]:
print("Accuracy Score: ", end = "")
print(accuracy_score(y,A))

Accuracy Score: 0.5
