In [158]:
import pandas as pd
import numpy as np
from collections import Counter
from sklearn.metrics import accuracy_score,confusion_matrix

In [159]:
df = pd.read_csv("fruit_data_with_colors.txt",delimiter = "\t")


In [160]:
df.head()

fruit_label fruit_name fruit_subtype  mass  width  height  color_score
0            1      apple  granny_smith   192    8.4     7.3         0.55
1            1      apple  granny_smith   180    8.0     6.8         0.59
2            1      apple  granny_smith   176    7.4     7.2         0.60
3            2   mandarin      mandarin    86    6.2     4.7         0.80
4            2   mandarin      mandarin    84    6.0     4.6         0.79

In [161]:
X = df[["mass","width","height"]]

In [162]:
Y = df["fruit_label"]

In [163]:
trainX = np.array(X[:50])
trainY = np.array(Y[:50])
testX = np.array(X[50:])
testY = np.array(Y[50:])


In [164]:
class KNN:
    def __init__(self,k = 1):
        self.k = k
        
    def euclidian_distance(self,query,X):
        difference = np.array(X) - np.array(query)
        sqrd_diff = np.square(difference)
        sum_sqrd_diff = np.sum(sqrd_diff, axis = 1)
        distance = np.sqrt(sum_sqrd_diff)
        return distance
    
    def nearest_neighbours(self,distance):
        return np.argsort(distance)[:self.k]
    
    def predict(self,query,trainX,trainY):
        ed = self.euclidian_distance(query,trainX)
        nn = self.nearest_neighbours(ed)
        labels_nn = list(trainY[nn])
        return max(labels_nn, key = labels_nn.count) 
    

In [185]:

for i in (1,3,5,7):
    classifier = KNN(i)
    predictions = [classifier.predict(x,X_array,Y_array) for x in dX_array]
    preds=np.array(predictions)
    print("Predicted Outcomes With K=",i)
    print(preds)

    print("Actual Outcomes:")
    print(testY, end = "\n\n")

    print("Accuracy Score: ")
    print(accuracy_score(testY,predictions))

    print("Confusion Matrix: ")
    print(confusion_matrix(testY,predictions))
    print("\n")

Predicted Outcomes With K= 1
[[4]
 [4]
 [4]
 [4]
 [4]
 [4]
 [4]
 [1]
 [4]]
Actual Outcomes:
[4 4 4 4 4 4 4 4 4]

Accuracy Score: 
0.8888888888888888
Confusion Matrix: 
[[0 0]
 [1 8]]


Predicted Outcomes With K= 3
[[4]
 [4]
 [4]
 [4]
 [4]
 [4]
 [4]
 [3]
 [4]]
Actual Outcomes:
[4 4 4 4 4 4 4 4 4]

Accuracy Score: 
0.8888888888888888
Confusion Matrix: 
[[0 0]
 [1 8]]


Predicted Outcomes With K= 5
[[3]
 [3]
 [3]
 [3]
 [3]
 [3]
 [3]
 [3]
 [3]]
Actual Outcomes:
[4 4 4 4 4 4 4 4 4]

Accuracy Score: 
0.0
Confusion Matrix: 
[[0 0]
 [9 0]]


Predicted Outcomes With K= 7
[[3]
 [3]
 [3]
 [3]
 [3]
 [3]
 [3]
 [3]
 [3]]
Actual Outcomes:
[4 4 4 4 4 4 4 4 4]

Accuracy Score: 
0.0
Confusion Matrix: 
[[0 0]
 [9 0]]


